Units table schema:
```python
    Schema([
        ('is_qc_pass', Boolean),
        ('snr', Float64),
        ('firing_rate', Float64),
        ('decoder_label', String),
        ('location', String),
        ...
        ('spike_amplitudes', List(Float32)),
        ('spike_times', List(Float64)),
        ...
        ('waveform_mean', Array(Float64, shape=(210, 384))),
        ('waveform_sd', Array(Float64, shape=(210, 384))),
    ])
```

The units table can be expensive to load from S3 when each NWB file contains thousands of units.

In practice, we often just want to filter for `is_qc_pass == true` and a target CCF structure, then fetch only
the columns needed for the analysis, such as `spike_times` or waveform data for the selected units.

---

**Can we make a query API that downloads just the data we need?**

In [2]:
import lazynwb
import polars as pl
import upath        # pathlib-like API for remote filesystems

lazynwb.config.anon = True  # access public S3 buckets without credentials
lazynwb.__version__

'1.0.0.dev3'

In [4]:
nwb_dir = upath.UPath("s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284", anon=True)
components_dir = upath.UPath("s3://aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284", anon=True)

tuple(components_dir.iterdir())

(S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/aud_rf_mapping', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/devices', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/electrode_groups', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/electrodes', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/epochs', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/invalid_times', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/optotagging', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/performance', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/session', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/subject', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/trials', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/units', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/vis_rf_mapping', protocol='s3'))

In [7]:
tuple((components_dir/ 'consolidated').iterdir())

(S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/aud_rf_mapping.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/devices.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/electrode_groups.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/epochs.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/invalid_times.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/licks.zarr', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/optotagging.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/performance.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/running_speed.zarr', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/session.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/spike_times.zarr', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/subject.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/trials.parquet', protocol='s3'),
 S3Path('aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/vis_rf_mapping.parquet', protocol='s3'))

In [14]:
lf = pl.scan_parquet(
    's3://aind-scratch-data/dynamic-routing/cache/nwb_components/v0.0.284/consolidated/trials.parquet',
    storage_options={'skip_signature': 'true'},
)
lf.collect()

shape: (116_270, 64)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ start_tim ┆ stop_time ┆ quiescent ┆ quiescent ┆ … ┆ opto_labe ┆ opto_powe ┆ opto_stim ┆ is_singl │
│ e         ┆ ---       ┆ _start_ti ┆ _stop_tim ┆   ┆ l         ┆ r         ┆ _name     ┆ e_opto_l │
│ ---       ┆ f64       ┆ me        ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ocation  │
│ f64       ┆           ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64       ┆ str       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 111.21154 ┆ 115.71493 ┆ 111.21154 ┆ 112.67913 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 116.09859 ┆ 120.60244 ┆ 116.09859 ┆ 117.56693 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 120.78591 ┆ 125.2896  ┆ 120.78591 ┆ 122.25374 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 126.04027 ┆ 130.544   ┆ 126.04027 ┆ 127.50818 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 130.66081 ┆ 135.16464 ┆ 130.66081 ┆ 132.12864 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 3636.7158 ┆ 3642.2538 ┆ 3636.7158 ┆ 3638.2004 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 92        ┆ 68        ┆ 92        ┆ 89        ┆   ┆           ┆           ┆           ┆          │
│ 3649.9102 ┆ 3655.4816 ┆ 3649.9102 ┆ 3651.3781 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 9         ┆ 46        ┆ 9         ┆ 83        ┆   ┆           ┆           ┆           ┆          │
│ 3655.5483 ┆ 3661.0529 ┆ 3655.5483 ┆ 3657.0162 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 5         ┆ 9         ┆ 5         ┆ 76        ┆   ┆           ┆           ┆           ┆          │
│ 3662.9045 ┆ 3668.4925 ┆ 3662.9045 ┆ 3664.3890 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 39        ┆ 59        ┆ 39        ┆ 98        ┆   ┆           ┆           ┆           ┆          │
│ 3669.3932 ┆ 3674.8979 ┆ 3669.3932 ┆ 3670.8611 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 95        ┆ 41        ┆ 95        ┆ 81        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
expr = (
    pl.col('start_time').le(1300)
    & pl.col('is_vis_stim')
)
expr.meta.root_names()

['start_time', 'is_vis_stim']

In [29]:
lf.collect()['session_id'].n_unique()

221

In [27]:
lf.filter(expr, (pl.col('is_vis_stim'))).select('start_time', 'stim_name').collect()

shape: (4_648, 2)
┌─────────────┬───────────┐
│ start_time  ┆ stim_name │
│ ---         ┆ ---       │
│ f64         ┆ str       │
╞═════════════╪═══════════╡
│ 111.21154   ┆ vis1      │
│ 116.09859   ┆ vis1      │
│ 120.78591   ┆ vis1      │
│ 126.04027   ┆ vis1      │
│ 130.66081   ┆ vis1      │
│ …           ┆ …         │
│ 1254.668632 ┆ vis2      │
│ 1267.41265  ┆ vis1      │
│ 1273.61786  ┆ vis1      │
│ 1281.441075 ┆ vis2      │
│ 1299.289404 ┆ vis2      │
└─────────────┴───────────┘

In [ ]:
lazynwb.scan_nwb(tuple(nwb_dir.iterdir()), "trials")

In [37]:
lf.filter(expr).select('start_time').head().collect()

Getting multi-NWB intervals/trials table:  15%|█████▊                                | 36/233 [00:00<00:01, 127.72NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/660023_2023-08-08.nwb
Getting multi-NWB intervals/trials table:  21%|███████▉                              | 49/233 [00:00<00:01, 124.65NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/664566_2023-11-20.nwb
Getting multi-NWB intervals/trials table:  58%|█████████████████████▎               | 134/233 [00:01<00:00, 119.33NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/721536_2024-05-16.nwb
Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/724612_2024-07-24.nwb
Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/724612_2024-07-22.nwb
Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/721536_2024-05-17.nwb
Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/724612_2024-07-25.nwb
Getting multi-NWB intervals/trials table:  64%|███████████████████████▌             | 148/233 [00:01<00:00, 118.01NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/736803_2024-08-13.nwb
Getting multi-NWB intervals/trials table:  76%|████████████████████████████         | 177/233 [00:01<00:00, 124.35NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/754852_2025-02-10.nwb
Getting multi-NWB intervals/trials table:  82%|██████████████████████████████▍      | 192/233 [00:01<00:00, 130.13NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/754852_2025-02-12.nwb
Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/754852_2025-02-11.nwb
Getting multi-NWB intervals/trials table:  89%|████████████████████████████████▊    | 207/233 [00:01<00:00, 135.42NWB/s]Table 'intervals/trials' not found in s3://aind-scratch-data/dynamic-routing/cache/nwb/v0.0.284/754852_2025-02-13.nwb
Getting multi-NWB intervals/trials table: 100%|█████████████████████████████████████| 233/233 [00:01<00:00, 130.62NWB/s]

shape: (5, 1)
┌────────────┐
│ start_time │
│ ---        │
│ f64        │
╞════════════╡
│ 111.21154  │
│ 116.09859  │
│ 120.78591  │
│ 126.04027  │
│ 130.66081  │
└────────────┘

In [38]:
units_lf = lazynwb.scan_nwb(tuple(nwb_dir.iterdir())[:10], "units")

In [39]:
units_lf

In [50]:
units_lf.collect_schema()

Schema([('activity_drift', Float64),
        ('amplitude', Float64),
        ('amplitude_cutoff', Float64),
        ('amplitude_cv_median', Float64),
        ('amplitude_cv_range', Float64),
        ('amplitude_median', Float64),
        ('ccf_ap', Float64),
        ('ccf_dv', Float64),
        ('ccf_ml', Float64),
        ('channels', List(Int64)),
        ('cluster_id', Int64),
        ('d_prime', Float64),
        ('decoder_label', String),
        ('decoder_probability', Float64),
        ('default_qc', Boolean),
        ('device_name', String),
        ('drift_mad', Float64),
        ('drift_ptp', Float64),
        ('drift_std', Float64),
        ('electrode_group', String),
        ('electrode_group_name', String),
        ('electrodes', List(Int64)),
        ('exp_decay', Float64),
        ('firing_range', Float64),
        ('firing_rate', Float64),
        ('half_width', Float64),
        ('id', Int64),
        ('is_not_drift', Boolean),
        ('is_qc_pass', Boolean),
        ('isi_violations_count', Float64),
        ('isi_violations_ratio', Float64),
        ('isolation_distance', Float64),
        ('l_ratio', Float64),
        ('location', String),
        ('nn_hit_rate', Float64),
        ('nn_miss_rate', Float64),
        ('num_negative_peaks', Int64),
        ('num_positive_peaks', Int64),
        ('num_spikes', Float64),
        ('obs_intervals', List(Array(Float64, shape=(2,)))),
        ('peak_channel', Int64),
        ('peak_electrode', Int64),
        ('peak_to_valley', Float64),
        ('peak_trough_ratio', Float64),
        ('peak_waveform_index', Int64),
        ('presence_ratio', Float64),
        ('recovery_slope', Float64),
        ('repolarization_slope', Float64),
        ('rp_contamination', Float64),
        ('rp_violations', Float64),
        ('silhouette', Float64),
        ('sliding_rp_violation', Float64),
        ('snr', Float64),
        ('spike_amplitudes', List(Float32)),
        ('spike_times', List(Float64)),
        ('spread', Float64),
        ('structure', String),
        ('sync_spike_2', Float64),
        ('sync_spike_4', Float64),
        ('sync_spike_8', Float64),
        ('unit_id', String),
        ('velocity_above', Float64),
        ('velocity_below', Float64),
        ('waveform_mean', Array(Float64, shape=(210, 384))),
        ('waveform_sd', Array(Float64, shape=(210, 384))),
        ('_nwb_path', String),
        ('_table_path', String),
        ('_table_index', UInt32)])

In [ ]:
lazynwb.get_internal_paths(tuple(nwb_dir.iterdir())[10])

['/acquisition/frametimes_eye_camera',
 '/acquisition/frametimes_front_camera',
 '/acquisition/frametimes_side_camera',
 '/intervals/epochs',
 '/intervals/performance',
 '/intervals/trials',
 '/processing/behavior/dlc_eye_camera',
 '/processing/behavior/eye_tracking',
 '/processing/behavior/facemap_front_camera',
 '/processing/behavior/facemap_side_camera',
 '/processing/behavior/licks',
 '/processing/behavior/lp_front_camera',
 '/processing/behavior/lp_side_camera',
 '/processing/behavior/quiescent_interval_violations',
 '/processing/behavior/rewards',
 '/processing/behavior/running_speed',
 '/processing/ecephys',
 '/units']

In [62]:
lazynwb.scan_nwb(tuple(nwb_dir.iterdir())[:10], "processing/behavior/facemap_side_camera").collect_schema()

Schema([('data', Array(Float32, shape=(500,))),
        ('timestamps', Float64),
        ('_nwb_path', String),
        ('_table_path', String),
        ('_table_index', UInt32)])

In [63]:
lazynwb.scan_nwb(tuple(nwb_dir.iterdir())[:10], "processing/behavior/facemap_side_camera").head().collect()

shape: (5, 5)
┌───────────────────────┬────────────┬───────────────────────┬──────────────────────┬──────────────┐
│ data                  ┆ timestamps ┆ _nwb_path             ┆ _table_path          ┆ _table_index │
│ ---                   ┆ ---        ┆ ---                   ┆ ---                  ┆ ---          │
│ array[f32, 500]       ┆ f64        ┆ str                   ┆ str                  ┆ u32          │
╞═══════════════════════╪════════════╪═══════════════════════╪══════════════════════╪══════════════╡
│ [146.792786,          ┆ NaN        ┆ s3://aind-scratch-dat ┆ processing/behavior/ ┆ 0            │
│ 533.920288, … -3.…    ┆            ┆ a/dynamic…            ┆ facemap_si…          ┆              │
│ [146.792786,          ┆ 67.28383   ┆ s3://aind-scratch-dat ┆ processing/behavior/ ┆ 1            │
│ 533.920288, … -3.…    ┆            ┆ a/dynamic…            ┆ facemap_si…          ┆              │
│ [-269.191437,         ┆ 67.3005    ┆ s3://aind-scratch-dat ┆ processing/behavior/ ┆ 2            │
│ -133.109772, … 5…     ┆            ┆ a/dynamic…            ┆ facemap_si…          ┆              │
│ [-268.062378,         ┆ 67.31716   ┆ s3://aind-scratch-dat ┆ processing/behavior/ ┆ 3            │
│ -136.619492, … -…     ┆            ┆ a/dynamic…            ┆ facemap_si…          ┆              │
│ [-273.905548,         ┆ 67.33383   ┆ s3://aind-scratch-dat ┆ processing/behavior/ ┆ 4            │
│ -137.816864, … 1…     ┆            ┆ a/dynamic…            ┆ facemap_si…          ┆              │
└───────────────────────┴────────────┴───────────────────────┴──────────────────────┴──────────────┘

In [ ]:
(
    units_lf
    .filter(
        pl.col('is_qc_pass'),
        pl.col('structure') == 'ACAd',
    )
    .select(
        'location',
        'spike_times',
        '_nwb_path',
    )
).collect()

Getting multi-NWB units table: 100%|███████████████████████████████████████████████████| 10/10 [00:00<00:00, 54.39NWB/s]
Getting multi-NWB units table: 100%|█████████████████████████████████████████████████████| 3/3 [00:00<00:00,  6.72NWB/s]

shape: (34, 3)
┌──────────┬─────────────────────────────────┬─────────────────────────────────┐
│ location ┆ spike_times                     ┆ _nwb_path                       │
│ ---      ┆ ---                             ┆ ---                             │
│ str      ┆ list[f64]                       ┆ str                             │
╞══════════╪═════════════════════════════════╪═════════════════════════════════╡
│ ACAd6a   ┆ [160.234066, 190.667436, … 479… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [17.921598, 18.063131, … 4816.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [20.580726, 22.092056, … 4812.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [18.247331, 20.257327, … 4816.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [20.117027, 20.35296, … 4815.8… ┆ s3://aind-scratch-data/dynamic… │
│ …        ┆ …                               ┆ …                               │
│ ACAd6a   ┆ [33.089217, 33.149483, … 4873.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [36.543874, 47.783975, … 4873.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [31.459021, 31.486088, … 4873.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [31.977653, 32.006653, … 4872.… ┆ s3://aind-scratch-data/dynamic… │
│ ACAd6a   ┆ [31.713254, 31.876887, … 4873.… ┆ s3://aind-scratch-data/dynamic… │
└──────────┴─────────────────────────────────┴─────────────────────────────────┘

In [48]:
units_df = _
units_df['_nwb_path'].n_unique()

3

In [51]:
units_df.select(pl.col('spike_times').list.len())

shape: (34, 1)
┌─────────────┐
│ spike_times │
│ ---         │
│ u32         │
╞═════════════╡
│ 566         │
│ 39763       │
│ 4293        │
│ 5984        │
│ 2765        │
│ …           │
│ 29548       │
│ 7286        │
│ 44504       │
│ 5734        │
│ 53123       │
└─────────────┘